Repository SOPT-all/36-COLLABORATION-WEB-INTERPARK-TICKET, pull requests merged in 2025-05, with the labels that each got.

#2 chore: TEMPLATE 파일 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/pull_request_template.md
Labels: 서희, chore

#4 chore: vercel 파일 생성
  .github/workflows/ci-cd.yml
  .github/workflows/deploy.yml
  vercel.json
Labels: 소이, setting

#5 chore : set up eslint and prettier
  .eslintrc
  .prettierrc
  eslint.config.js
  package-lock.json
  package.json
  yarn.lock
Labels: 재림, setting

#8 chore: reset.css 폰트 크기 설정 추가
  src/shared/styles/reset.css.ts
Labels: 예지, chore

#12 chore: 폰트 스타일 수정
  src/pages/Main/MainPage.css.ts
  src/shared/styles/tokens.css.ts
Labels: 예지, setting

#47 feat: rectangle component
  package.json
  src/pages/Payment/api/payment.ts
  src/pages/Payment/components/Container/BankContainer.tsx
  src/pages/Payment/components/Container/Btn/Btn.css.ts
  src/pages/Payment/components/Container/Btn/Btn.tsx
  src/pages/Payment/components/Container/Container.css.ts
  src/pages/Payment/components/Container/MethodContainer.tsx
  src/pages/Payment/components/CustomCheckbox.tsx
  src/pages/Payment/components/Dropdown/ListCheck/ListCheck.css.ts
  src/pages/Payment/components/Dropdown/ListCheck/ListCheck.tsx
  src/pages/Payment/components/Dropdown/ListCheckMiddle/ListCheckMiddle.css.ts
  src/pages/Payment/components/Dropdown/ListCheckMiddle/ListCheckMiddle.tsx
  src/pages/Payment/components/Dropdown/ListPoint/ListPoint.css.ts
  src/pages/Payment/components/Dropdown/ListPoint/ListPoint.tsx
  src/pages/Payment/components/Dropdown/listInfo/ListInfo.css.ts
  src/pages/Payment/components/Dropdown/listInfo/ListInfo.tsx
  src/pages/Payment/components/Rectangle/Rectangle.css.ts
  src/pages/Payment/components/Rectangle/Rectangle.tsx
  src/pages/Payment/components/TextField/Text-Field.css.ts
  src/pages/Payment/components/TextField/Text-Field.tsx
  src/shared/assets/icon/checkbox_fill.svg
  src/shared/assets/icon/checkbox_unfill.svg
  src/shared/assets/icon/ic_arrow_down_gray50_18.svg
  src/shared/assets/icon/ic_check_blue80_18.svg
  src/shared/assets/icon/ic_check_gray30_18.svg
  src/shared/assets/icon/ic_payment_28(1).svg
  src/shared/assets/icon/ic_payment_28(2).svg
  src/shared/assets/icon/ic_payment_28(3).svg
  src/shared/assets/icon/ic_payment_28.svg
  src/shared/assets/vector/Vector 29_gray20.svg
  src/shared/assets/vector/Vector 29_gray70.svg
  src/shared/types/svg.d.ts
  vite.config.ts
  yarn.lock
Labels: 서희, feature, style

#9 feat: 좌석 선택 컴포넌트 구현
  package.json
  src/pages/ComponentTest/ComponentTest.tsx
  src/router/router.tsx
  src/shared/assets/icon/ic_R_seat.svg
  src/shared/assets/icon/ic_S_seat.svg
  src/shared/components/.gitkeep
  src/shared/components/SeatSelectChip/SeatSelectChip.css.ts
  src/shared/components/SeatSelectChip/SeatSelectChip.tsx
  yarn.lock
Labels: 예지, style

#15 feat: 예매, 일시변경, 등록 버튼 컴포넌트 구현
  src/shared/components/BookingButton/BookingButton.css.ts
  src/shared/components/BookingButton/BookingButton.tsx
  src/shared/components/ChangeButton/ChangeButton.css.ts
  src/shared/components/ChangeButton/ChangeButton.tsx
  src/shared/components/RegisterButton/Register.css.ts
  src/shared/components/RegisterButton/RegisterButton.tsx
Labels: 예지, style

#17 feat: btn-small, btn-large 버튼 컴포넌트 구현
  src/shared/components/LargeButton/LargeButton.css.ts
  src/shared/components/LargeButton/LargeButton.tsx
  src/shared/components/SmallButton/SmallButton.css.ts
  src/shared/components/SmallButton/SmallButton.tsx
Labels: 예지, style

#24 feat: Home 전체보기 버튼 컴포넌트 구현
  package.json
  src/pages/ComponentTest/ComponentTest.tsx
  src/shared/assets/icon/ic_arrow_right_gray70_16.svg
  src/shared/components/HomeAddButton/HomeAddButton.css.ts
  src/shared/components/HomeAddButton/HomeAddButton.tsx
  src/shared/components/SeatSelectChip/SeatSelectChip.tsx
  vite.config.ts
  yarn.lock
Labels: 소이, style

#25 feat: 예금주 정보 카드 컴포넌트 구현
  src/pages/ComponentTest/ComponentTest.tsx
  src/shared/components/BankInfoCard/BankInfoCard.css.ts
  src/shared/components/BankInfoCard/BankInfoCard.tsx
Labels: 소이, style

#26 feat: 공연 정보 컴포넌트 구현
  src/shared/assets/image/img_pride_content_info.png
  src/shared/components/CardContentInfo/CardContentInfo.css.ts
  src/shared/components/CardContentInfo/CardContentInfo.tsx
Labels: 예지, style

#28 feat: 푸터 컴포넌트 구현
  src/shared/assets/icon/ic_arrow_down_gray60_12.svg
  src/shared/assets/icon/ic_card_brand.svg
  src/shared/components/Footer/Footer.css.ts
  src/shared/components/Footer/Footer.tsx
  src/shared/styles/tokens.css.ts
Labels: 예지, style

#39 feat: 좌석 페이지 팝업창 구현
  src/shared/components/Popup/Popup.css.ts
  src/shared/components/Popup/Popup.tsx
Labels: 재림, style

#41 feat : 뱃지 컴포넌트
  src/shared/components/Badge/Badge.css.ts
  src/shared/components/Badge/Badge.tsx
Labels: 재림, style

#44 feat : 메인페이지 공연박스 컴포넌트
  src/pages/Main/MainPage.tsx
  src/shared/components/main/Perform/InfoCard.css.ts
  src/shared/components/main/Perform/InfoCard.tsx
Labels: 재림, feature

#49 feat: 타임딜 뱃지 컴포넌트
  src/pages/Main/MainPage.tsx
  src/shared/components/TimeDeal/TimeDeal.css.ts
  src/shared/components/TimeDeal/TimeDeal.tsx
Labels: 재림, feature

#32 feat: 좌석 선택 bottom sheet 컴포넌트 구현
  src/pages/ComponentTest/ComponentTest.tsx
  src/pages/Main/MainPage.tsx
  src/router/router.tsx
  src/shared/components/BankInfoCard/BankInfoCard.css.ts
  src/shared/components/BankInfoCard/BankInfoCard.tsx
  src/shared/components/HomeAddButton/HomeAddButton.css.ts
  src/shared/components/HomeAddButton/HomeAddButton.tsx
  src/shared/components/SeatBottomSheet/SeatBottomSheet.css.ts
  src/shared/components/SeatBottomSheet/SeatBottomSheet.tsx
  src/shared/components/SeatSelectChip/SeatSelectChip.css.ts
Labels: 소이, style

#45 feat: 날짜 선택 회차 카드 컴포넌트 구현
  src/pages/Main/MainPage.tsx
  src/shared/components/DateReservationCard/DateReservationCard.css.ts
  src/shared/components/DateReservationCard/DateReservationCard.tsx
Labels: 소이, style

#34 feat: dropdown component 구현
  package.json
  src/pages/Payment/components/Dropdown/ListCheck/ListCheck.css.ts
  src/pages/Payment/components/Dropdown/ListCheck/ListCheck.tsx
  src/pages/Payment/components/Dropdown/ListCheckMiddle/ListCheckMiddle.css.ts
  src/pages/Payment/components/Dropdown/ListCheckMiddle/ListCheckMiddle.tsx
  src/pages/Payment/components/Dropdown/ListPoint/ListPoint.css.ts
  src/pages/Payment/components/Dropdown/ListPoint/ListPoint.tsx
  src/pages/Payment/components/Dropdown/listInfo/ListInfo.css.ts
  src/pages/Payment/components/Dropdown/listInfo/ListInfo.tsx
  src/router/router.tsx
  src/shared/assets/icon/checkbox_fill.svg
  src/shared/assets/icon/checkbox_unfill.svg
  src/shared/assets/icon/ic_arrow_down_gray50_18.svg
  src/shared/assets/icon/ic_check_blue80_18.svg
  src/shared/assets/icon/ic_check_gray30_18.svg
  src/shared/assets/icon/ic_payment_28(1).svg
  src/shared/assets/icon/ic_payment_28(2).svg
  src/shared/assets/icon/ic_payment_28(3).svg
  src/shared/assets/icon/ic_payment_28.svg
  src/shared/types/svg.d.ts
  vite.config.ts
  yarn.lock
Labels: 서희, feature

#36 feat: textfield 구현
  src/pages/Payment/components/TextField/TextField.css.ts
  src/pages/Payment/components/TextField/TextField.tsx
Labels: 서희, feature

#57 feat: bankinfo 파일 추가
  src/shared/components/BankInfo/BankInfoCard.css.ts
  src/shared/components/BankInfo/BankInfoCard.tsx
Labels: 소이, style

#59 feat: 홈 전체보기 버튼 컴포넌트 파일 추가
  src/shared/components/HomeMoreButton/HomeMoreButton.css.ts
  src/shared/components/HomeMoreButton/HomeMoreButton.tsx
Labels: 소이, style

#64 chore: 빌드 오류 해결을 위한 포맷팅 수행
  src/shared/components/BankInfo/BankInfoCard.css.ts
  src/shared/components/BankInfo/BankInfoCard.tsx
  src/shared/components/HomeMoreButton/HomeMoreButton.css.ts
  src/shared/components/HomeMoreButton/HomeMoreButton.tsx
Labels: 예지, fix

#62 chore: 불필요 파일 삭제
  src/pages/Payment/components/CustomCheckbox.tsx
  src/pages/Payment/components/CustomCheckbox/CustomCheckbox.tsx
  src/pages/Payment/components/TextField/Text-Field.css.ts
  src/pages/Payment/components/TextField/Text-Field.tsx
Labels: 서희, chore

#75 feat: 홈화면 메인 섹션 구현
  src/pages/Main/MainPage.css.ts
  src/pages/Main/MainPage.tsx
  src/shared/assets/icon/category_camping.svg
  src/shared/assets/icon/category_classic.svg
  src/shared/assets/icon/category_concert.svg
  src/shared/assets/icon/category_display.svg
  src/shared/assets/icon/category_family.svg
  src/shared/assets/icon/category_musical.svg
  src/shared/assets/icon/category_nolcard.svg
  src/shared/assets/icon/category_sport.svg
  src/shared/assets/icon/category_theater.svg
  src/shared/assets/icon/category_topping.svg
  src/shared/assets/icon/home_card_banner.svg
  src/shared/constants/Categories.ts
Labels: 소이, style

#68 feat : 할인중 공연 컴포넌트
  src/pages/Main/components/Discount/DiscountCard.css.ts
  src/pages/Main/components/Discount/DiscoutCard.tsx
Labels: 재림, feature

#69 feat: 좌석 선택 컴포넌트 구현
  src/pages/SeatSelect/SeatSelectPage.css.ts
  src/pages/SeatSelect/SeatSelectPage.tsx
  src/pages/SeatSelect/components/SeatCard/Seat.css.ts
  src/pages/SeatSelect/components/SeatCard/Seat.tsx
  src/pages/SeatSelect/components/SeatCard/SeatCard.css.ts
  src/pages/SeatSelect/components/SeatCard/SeatCard.tsx
  src/pages/SeatSelect/components/SeatCard/SeatRow.css.ts
  src/pages/SeatSelect/components/SeatCard/SeatRow.tsx
  src/pages/SeatSelect/components/StageText/StageText.css.ts
  src/pages/SeatSelect/components/StageText/StageText.tsx
  src/pages/SeatSelect/types/SeatData.ts
  src/router/router.tsx
Labels: 예지, feature

#78 feat : 날짜 선택 페이지
  src/pages/SelectDate/SelectDatePage.css.ts
  src/pages/SelectDate/SelectDatePage.tsx
  src/router/router.tsx
  src/shared/components/Calendar/Calendar.css.ts
  src/shared/components/Calendar/Calendar.tsx
  src/shared/components/CardContentInfo/CardContentInfo.css.ts
  src/shared/components/CardContentInfo/CardContentInfo.tsx
  src/shared/components/DateReservationCard/DateReservationCard.css.ts
  src/shared/styles/tokens.css.ts
Labels: 재림, feature

#80 feat : 메인페이지 - 장르별 맵핑 섹션
  src/pages/Main/MainPage.tsx
  src/pages/Main/components/CategoryTab/CategoryTab.css.ts
  src/pages/Main/components/CategoryTab/CategoryTab.tsx
  src/pages/Main/components/Genre/Genre.css.ts
  src/pages/Main/components/Genre/Genre.tsx
  src/shared/components/HomeMoreButton/HomeMoreButton.css.ts
  src/shared/components/main/Perform/InfoCard.css.ts
Labels: 재림, feature

#82 feat : 메인페이지 - MD픽 섹션
  src/pages/Main/components/CategoryTab/CategoryTab.css.ts
  src/pages/Main/components/CategoryTab/CategoryTab.tsx
  src/pages/Main/components/MdPick/MdPick.css.ts
  src/pages/Main/components/MdPick/MdPick.tsx
Labels: 재림, feature

#91 feat: payment step3 view/#85
  src/pages/Payment/Payment.css.ts
  src/pages/Payment/Step1.tsx
  src/pages/Payment/Step3.tsx
  src/pages/Payment/components/BankInfo/BankInfoCard.css.ts
  src/pages/Payment/components/BankInfo/BankInfoCard.tsx
  src/pages/Payment/components/BankNotice/BankNotice.css.ts
  src/pages/Payment/components/BankNotice/BankNotice.tsx
  src/pages/Payment/components/Container/BankContainer.tsx
  src/pages/Payment/components/Container/MethodContainer.tsx
  src/pages/Payment/components/CustomCheckbox/CustomCheckbox.css.ts
  src/pages/Payment/components/Dropdown/ListCheck/ListCheck.css.ts
  src/pages/Payment/components/Dropdown/ListCheck/ListCheck.tsx
  src/pages/Payment/components/InfoPrice/InfoPrice.css.ts
  src/pages/Payment/components/InfoPrice/InfoPrice.tsx
  src/pages/Payment/components/InfoRowTitle/InfoRowTitle.css.ts
  src/pages/Payment/components/InfoRowTitle/InfoRowTitle.tsx
  src/pages/Payment/components/TicketPriceInfo/TicketPriceInfo.css.ts
  src/pages/Payment/components/TicketPriceInfo/TicketPriceInfo.tsx
  src/pages/Payment/components/TicketReceiveSelect/SelectOptionButton/SelectOptionButton.css.ts
  src/pages/Payment/components/TicketReceiveSelect/TicketReceicerSelectCard/TicketReceiveSelectCard.css.ts
  src/pages/Payment/components/TicketReceiveSelect/TicketReceicerSelectCard/TicketReceiveSelectCard.tsx
  src/shared/components/Rectangle/Rectangle.css.ts
Labels: 서희, feature, fix

#90 feat : 메인페이지 - 할인 중 공연 섹션
  src/pages/Main/MainPage.tsx
  src/pages/Main/components/Discount/DiscountCard.css.ts
  src/pages/Main/components/Discount/Discout.tsx
  src/pages/Main/components/Discount/DiscoutCard.tsx
  src/pages/Main/components/Genre/Genre.css.ts
  src/pages/Main/components/Genre/Genre.tsx
  src/shared/components/HomeMoreButton/HomeMoreButton.css.ts
Labels: 재림, feature

#87 setting: 네트워크 세팅 및 예시 API 코드
  .gitignore
  package.json
  src/App.tsx
  src/main.tsx
  src/pages/SeatSelect/api/api.ts
  src/pages/SeatSelect/api/hooks.ts
  src/pages/SeatSelect/api/types.ts
  src/router/router.tsx
  src/shared/constants/.gitkeep
  src/shared/constants/queryKey.ts
  src/shared/network/.gitkeep
  src/shared/network/axiosInstance.ts
  src/shared/network/baseResponse.ts
  src/shared/network/queryClient.ts
  src/shared/network/request.ts
  yarn.lock
Labels: 예지, feature, setting

#89 feat: 좌석 선택 페이지 구현
  index.html
  src/pages/SeatSelect/SeatSelectPage.css.ts
  src/pages/SeatSelect/SeatSelectPage.tsx
  src/pages/SeatSelect/components/Popup/Popup.css.ts
  src/pages/SeatSelect/components/Popup/Popup.tsx
  src/pages/SeatSelect/components/SeatBottomSheet/SeatBottomSheet.css.ts
  src/pages/SeatSelect/components/SeatBottomSheet/SeatBottomSheet.tsx
  src/pages/SeatSelect/components/SeatCard/SeatCard.tsx
  src/pages/SeatSelect/components/SeatCard/SeatRow.tsx
  src/pages/SeatSelect/components/SeatSelectChip/SeatSelectChip.css.ts
  src/pages/SeatSelect/components/SeatSelectChip/SeatSelectChip.tsx
  src/pages/SeatSelect/components/StageText/StageText.css.ts
  src/pages/SeatSelect/types/SeatData.ts
  src/shared/components/Header/SeatHeader/SeatHeader.css.ts
  src/shared/components/Header/SeatHeader/SeatHeader.tsx
  src/shared/components/Popup/Popup.tsx
  src/shared/styles/global.css.ts
Labels: 예지, feature

#97 fix: API 세팅 수정
  src/shared/network/axiosInstance.ts
  src/shared/network/baseResponse.ts
  src/shared/network/request.ts
Labels: 예지, fix

#93 feat: Home 뷰 완성 및 api 연동
  src/pages/Main/MainPage.css.ts
  src/pages/Main/MainPage.tsx
  src/pages/Main/api/api.ts
  src/pages/Main/api/hooks.ts
  src/pages/Main/api/types.ts
  src/pages/Main/components/Discount/DiscountCard.css.ts
  src/pages/Main/components/Discount/Discout.tsx
  src/pages/Main/components/Discount/DiscoutCard.tsx
  src/pages/Main/components/Genre/Genre.css.ts
  src/pages/Main/components/Genre/Genre.tsx
  src/pages/Main/components/KeyWord/KeyWordSection.tsx
  src/pages/Main/components/MdPick/MdPick.css.ts
  src/pages/Main/components/MdPick/MdPick.tsx
  src/pages/Main/components/NOL PLAY/NolPlaySection.css.ts
  src/pages/Main/components/NOL PLAY/NolPlaySection.tsx
  src/pages/Main/components/Planned/PlannedSection.css.ts
  src/pages/Main/components/Planned/PlannedSection.tsx
  src/pages/Main/mockData/mockData.tsx
  src/shared/assets/icon/bar_navigation.svg
  src/shared/assets/icon/keyword_sangsang.svg
  src/shared/assets/icon/nolplay_first.svg
  src/shared/assets/icon/nolplay_video_first.svg
  src/shared/assets/icon/planned_expected_first.svg
  src/shared/components/Badge/Badge.css.ts
  src/shared/components/Badge/Badge.tsx
  src/shared/components/HomeMoreButton/HomeMoreButton.css.ts
  src/shared/components/Rectangle/Rectangle.css.ts
  src/shared/components/Rectangle/Rectangle.tsx
  src/shared/components/TimeDeal/TimeDeal.css.ts
  src/shared/components/main/Perform/InfoCard.css.ts
  src/shared/components/main/Perform/InfoCard.tsx
  src/shared/network/axiosInstance.ts
Labels: 소이, refactor, feature, style

#99 feat : 날짜 선택 페이지 API 연동
  src/pages/SelectDate/SelectDatePage.tsx
  src/pages/SelectDate/api/api.ts
  src/pages/SelectDate/api/hooks.ts
  src/pages/SelectDate/api/types.ts
  src/pages/SelectDate/utils/utils.ts
  src/shared/components/BookingButton/BookingButton.tsx
  src/shared/components/CardContentInfo/CardContentInfo.tsx
  src/shared/components/DateReservationCard/DateReservationCard.tsx
Labels: 재림, feature

#100 feat: 좌석 상태 조회, 좌석 선택 API 연동
  src/pages/Payment/Step1.tsx
  src/pages/Payment/components/Booking/BookingInfoSection.tsx
  src/pages/SeatSelect/SeatSelectPage.tsx
  src/pages/SeatSelect/api/api.ts
  src/pages/SeatSelect/api/hooks.ts
  src/pages/SeatSelect/api/types.ts
  src/pages/SeatSelect/components/SeatBottomSheet/SeatBottomSheet.tsx
  src/pages/SeatSelect/components/SeatCard/Seat.tsx
  src/pages/SeatSelect/components/SeatCard/SeatCard.tsx
  src/pages/SeatSelect/components/SeatCard/SeatRow.tsx
  src/pages/SeatSelect/components/SeatSelectChip/SeatSelectChip.tsx
  src/pages/SeatSelect/types/SeatData.ts
Labels: 예지, feature

#102 feat: nav 컴포넌트 구현
  src/shared/assets/icon/nav_category.svg
  src/shared/assets/icon/nav_home.svg
  src/shared/assets/icon/nav_my.svg
  src/shared/assets/icon/nav_search.svg
  src/shared/components/main/NavBar/NavBar.css.ts
  src/shared/components/main/NavBar/NavBar.tsx
  src/shared/constants/navItems.ts
Labels: 소이, style

#107 design: 홈에 nav 추가하고 스타일 수정, 필요없는 주석 제거
  src/pages/Main/MainPage.css.ts
  src/pages/Main/MainPage.tsx
  src/pages/Main/api/types.ts
  src/pages/Main/components/Discount/Discout.tsx
  src/pages/Main/components/Discount/DiscoutCard.tsx
  src/shared/components/main/NavBar/NavBar.css.ts
Labels: 소이, chore, style

#103 feat: payment api/#94
  src/pages/Payment/Payment.css.ts
  src/pages/Payment/Step1.tsx
  src/pages/Payment/Step2.tsx
  src/pages/Payment/Step3.tsx
  src/pages/Payment/api/banks.api.ts
  src/pages/Payment/api/banks.hooks.ts
  src/pages/Payment/api/banks.types.ts
  src/pages/Payment/api/payment.api.ts
  src/pages/Payment/api/payment.hooks.ts
  src/pages/Payment/api/payment.ts
  src/pages/Payment/api/payment.types.ts
  src/pages/Payment/api/ticketReceive.ts
  src/pages/Payment/components/Container/BankContainer.tsx
  src/pages/Payment/components/Container/Btn/Btn.css.ts
  src/pages/Payment/components/TextField/PhoneTextField.tsx
  src/pages/Payment/components/TextField/TextField.tsx
  src/pages/Payment/components/TextField/hooks/useFocusInput.ts
  src/pages/Payment/components/TicketPriceInfo/TicketPriceInfo.css.ts
  src/pages/Payment/constants/banks.ts
  src/pages/Payment/store/paymentStore.ts
  src/shared/constants/queryKey.ts
Labels: 서희, refactor, feature, fix

#109 refactor: 디테일 수정 및 개선
  src/pages/Main/MainPage.tsx
  src/pages/SeatSelect/SeatSelectPage.tsx
  src/pages/SeatSelect/components/Popup/Popup.css.ts
  src/pages/SeatSelect/components/Popup/Popup.tsx
  src/pages/SelectDate/SelectDatePage.tsx
  src/shared/components/Header/PayHeader/PayHeader.css.ts
  src/shared/components/Header/PayHeader/PayHeader.tsx
  src/shared/components/Header/SeatHeader/SeatHeader.css.ts
  src/shared/components/Header/SeatHeader/SeatHeader.tsx
  src/shared/components/Spinner/Spinner.css.ts
  src/shared/components/Spinner/Spinner.tsx
  src/shared/styles/global.css.ts
Labels: 예지, refactor

#120 chore: 날짜 선택 페이지 컴포넌트 수정
  src/shared/components/CardContentInfo/CardContentInfo.css.ts
  src/shared/components/DateReservationCard/DateReservationCard.tsx
Labels: 소이, chore, style

#126 chore: 폴더구조 정리
  src/App.tsx
  src/pages/Main/MainPage.tsx
  src/pages/Main/api/.gitkeep
  src/pages/Main/components/.gitkeep
  src/pages/Main/components/Discount/Discout.tsx
  src/pages/Main/components/Discount/DiscoutCard.tsx
  src/pages/Main/components/Genre/Genre.tsx
  src/pages/Main/components/HomeMoreButton/HomeMoreButton.css.ts
  src/pages/Main/components/HomeMoreButton/HomeMoreButton.tsx
  src/pages/Main/components/InfoCard/InfoCard.css.ts
  src/pages/Main/components/InfoCard/InfoCard.tsx
  src/pages/Main/components/KeyWord/KeyWordSection.tsx
  src/pages/Main/components/MdPick/MdPick.tsx
  src/pages/Main/components/NavBar/NavBar.css.ts
  src/pages/Main/components/NavBar/NavBar.tsx
  src/pages/Main/components/Planned/Badge/Badge.css.ts
  src/pages/Main/components/Planned/Badge/Badge.tsx
  src/pages/Main/components/Planned/PlannedSection.tsx
  src/pages/Main/components/TimeDeal/TimeDeal.css.ts
  src/pages/Main/components/TimeDeal/TimeDeal.tsx
  src/pages/Main/hooks/.gitkeep
  src/pages/Payment/Step1.tsx
  src/pages/Payment/Step2.tsx
  src/pages/Payment/Step3.tsx
  src/pages/Payment/components/LargeButton/LargeButton.css.ts
  src/pages/Payment/components/LargeButton/LargeButton.tsx
  src/pages/SeatSelect/components/SeatBottomSheet/SeatBottomSheet.tsx
  src/pages/SeatSelect/components/SeatBottomSheet/SmallButton.css.ts
  src/pages/SeatSelect/components/SeatBottomSheet/SmallButton.tsx
  src/pages/SelectDate/SelectDatePage.tsx
  src/pages/SelectDate/components/BookingButton/BookingButton.css.ts
  src/pages/SelectDate/components/BookingButton/BookingButton.tsx
  src/pages/SelectDate/components/Calendar/Calendar.css.ts
  src/pages/SelectDate/components/Calendar/Calendar.tsx
  src/pages/SelectDate/components/Calendar/Day.tsx
  src/pages/SelectDate/components/CardContentInfo/CardContentInfo.css.ts
  src/pages/SelectDate/components/CardContentInfo/CardContentInfo.tsx
  src/pages/SelectDate/components/DateReservationCard/DateReservationCard.css.ts
  src/pages/SelectDate/components/DateReservationCard/DateReservationCard.tsx
  src/router.tsx
  src/shared/components/RegisterButton/Register.css.ts
  src/shared/components/RegisterButton/RegisterButton.tsx
  src/shared/hooks/.gitkeep
  src/shared/router/router.tsx
Labels: 예지, chore

#130 feat: 홈 장르 섹션 스켈레톤 추가
  src/pages/Main/components/Genre/Genre.tsx
  src/pages/Main/components/skeleton/ImageSkeleton.tsx
  src/pages/Main/components/skeleton/ImageSkeletonList.tsx
  src/pages/Main/components/skeleton/Skelton.css.ts
  src/shared/components/Spinner/Spinner.tsx
Labels: 소이, refactor, style

#134 style: NOL PLAY border-radius 추가
  src/pages/Main/components/NOL PLAY/NolPlaySection.css.ts
  src/pages/Main/components/NOL PLAY/NolPlaySection.tsx
Labels: 소이, style
